/*******************************************************************************

*   Copyright (c) Telechips Inc.


*   TCC Version 1.0

This source code contains confidential information of Telechips.

Any unauthorized use without a written permission of Telechips including not
limited to re-distribution in source or binary form is strictly prohibited.

This source code is provided "AS IS" and nothing contained in this source code
shall constitute any express or implied warranty of any kind, including without
limitation, any warranty of merchantability, fitness for a particular purpose
or non-infringement of any patent, copyright or other third party intellectual
property right.
No warranty is made, express or implied, regarding the information's accuracy,
completeness, or performance.

In no event shall Telechips be liable for any claim, damages or other
liability arising from, out of or in connection with this source code or
the use in the source code.

This source code is provided subject to the terms of a Mutual Non-Disclosure
Agreement between Telechips and Company.
*
*******************************************************************************/
#ifndef	_TCC_COMMON_CMD_H__
#define		_TCC_COMMON_CMD_H__


/******************************************************************************
* include
******************************************************************************/
//#include "main.h"
/******************************************************************************
* defines
******************************************************************************/
#define TCC_FILE_PATH_SIZE		1024
#define TCC_FILE_NAME_SIZE		1024

#define TCC_SPECTRUM_LEVEL_SIZE	7

/******************************************************************************
* typedefs & structure
******************************************************************************/

typedef enum
{
	TCC_CMD_NULL = 0,
	TCC_CMD_SEND,
	TCC_CMD_REPLY,
	TCC_CMD_IND,
	TCC_CMD_NUM
}	TCC_CMD_TYPE;

typedef enum
{
	TCC_OPCODE_NULL = 0,
	TCC_OPCODE_AUDIO_DEC,
	TCC_OPCODE_AUDIO_ENC,
	TCC_OPCODE_VIDEO_DEC,
	TCC_OPCODE_IMAGE_DEC,
	TCC_OPCODE_ISDBT_DEC,
	TCC_OPCODE_DTV_ISDBTFSEG_DEC,
	TCC_OPCODE_DXB_ISDBTFSEG_DEC,
	TCC_OPCODE_DTV_IPTV_DEC,
	TCC_OPCODE_DXB_IPTV_DEC,
	TCC_OPCODE_DVBT_DEC,
	TCC_OPCODE_DVBH_DEC,
	TCC_OPCODE_TDMB_DEC,
	TCC_OPCODE_ATSC_DEC,
	TCC_OPCODE_CAMERA,
	#ifdef TCC_SUBTITLE_INCLUDE
	TCC_OPCODE_SUBTITLE,
	#endif
	TCC_OPCODE_NUM
}	TCC_OPCODE_TYPE;

typedef enum
{
	TCC_OPERAND_NULL = 0,
	TCC_OPERAND_OPEN,
	TCC_OPERAND_CLOSE,
	TCC_OPERAND_PLAY,
	TCC_OPERAND_RECODE,
	TCC_OPERAND_PAUSE,
	TCC_OPERAND_RESUME,
	TCC_OPERAND_STOP,
	TCC_OPERAND_STOP_IND,
	TCC_OPERAND_REC_STOP_IND,
	TCC_OPERAND_NEXT,
	TCC_OPERAND_PREVIOUS,
	TCC_OPERAND_EOF,
	TCC_OPERAND_FF_SEEK,
	TCC_OPERAND_REW_SEEK,
	TCC_OPERAND_SEEK,
	TCC_OPERAND_SCAN,
	TCC_OPERAND_VOLUME,
	TCC_OPERAND_INFO,
	TCC_OPERAND_GETCONTENTINFO,
	TCC_OPERAND_ALBUMART,
	TCC_OPERAND_FILEBRWS_INIT,
	TCC_OPERAND_FILEBRWS_PLAYLIST_ADD,
	TCC_OPERAND_FILEBRWS_PLAYLIST_DEL,
	TCC_OPERAND_PLAYLIST_ALBUMART,
	TCC_OPERAND_CURRENT,
	TCC_OPERAND_SUBTITLE_CURRENT,
	TCC_OPERAND_SUBTITLE_SINK_TIME,
	TCC_OPERAND_EQ,
	TCC_OPERAND_PLAYLIST_MODE,
	TCC_OPERAND_PLAYLIST,
	TCC_OPERAND_PLAYLIST_ADD,
	TCC_OPERAND_PLAYLIST_DEL,
	TCC_OPERAND_PLAYLIST_RESET,
	TCC_OPERAND_AB_REPEAT,
	TCC_OPERAND_THUMB,
	TCC_OPERAND_GET_THUMB,
	TCC_OPERAND_CAPTURE_SCREEN,
	TCC_OPERAND_CAPTURE_SCREEN_POPUP,
	TCC_OPERAND_ROTATION,
	TCC_OPERAND_ZOOM,
	TCC_OPERAND_EFFECTOUT,
	TCC_OPERAND_PAN,
	TCC_OPERAND_SLIDE,
	TCC_OPERAND_NEXT_FRAME,
	TCC_OPERAND_FRAME_SET,
	TCC_OPERAND_HDMI_SET,
	TCC_OPERAND_SEARCH,
	TCC_OPERAND_SEARCHED,
	TCC_OPERAND_SET2,
	TCC_OPERAND_SET_IP,
	TCC_OPERAND_SET_PID,
	TCC_OPERAND_SET_PMT,
	TCC_OPERAND_SET_PMT_IND,
	TCC_OPERAND_CHANGE_CHANNEL,
	TCC_OPERAND_SET_DISPLAY,
	TCC_OPERAND_SET_DISPLAY_ENABLE,
	TCC_OPERAND_SET_DISPLAY_DISABLE,
	TCC_OPERAND_TELETEXT_LOAD,
	TCC_OPERAND_SET_MUTE,
	TCC_OPERAND_CAPTION_DISP,
	TCC_OPERAND_GET_EPG,
	TCC_OPERAND_START_COMPLETE,
	TCC_OPERAND_SEARCH_CONTINUE,
	TCC_OPERAND_SEARCH_STOP,
	TCC_OPERAND_FREQ_RESET,
	TCC_OPERAND_FREQ_SETDONE,
	TCC_OPERAND_UNLOAD,
	TCC_OPERAND_EXIT,
	TCC_OPERAND_ERROR,
	TCC_OPERAND_PLAY_TIME_INFO,
	TCC_OPERAND_DEC_ERROR_INFO,
	TCC_OPERAND_DEC_START_MEASURE,
	TCC_OPERAND_DEC_CHANGE_SCREENMODE,
	TCC_OPERAND_DEC_SET_TVOUTMODE,
	TCC_OPERAND_DEC_SET_SCALEVALUE,
	TCC_OPERAND_DEC_SET_DEST_RESOLUTION,
	TCC_OPERAND_DEC_SET_OUTPUTMODE,
	TCC_OPERAND_DEC_SET_STEP,
	TCC_OPERAND_DEC_SET_SLOW,
	TCC_OPERAND_DEC_SET_DYNAMICRANGE,
	TCC_OPERAND_DEC_SET_SPDIF,
	TCC_OPERAND_DEC_HOTPLUG_STOP,
	TCC_OPERAND_SEND_SPUOUTPUT,
	TCC_OPERAND_SEND_PCIDATA,
	TCC_OPERAND_SUBTITLE_PLAY,
	TCC_OPERAND_SUBTITLE_PATH_PLAY,
	TCC_OPERAND_SUBTITLE_STOP,
	TCC_OPERAND_SUBTITLE_EXIT,
	TCC_OPERAND_SUBTITLE_SEEK,
	TCC_OPERAND_SUBTITLE_SHOW,
	TCC_OPERAND_SUBTITLE_HIDE,
	TCC_OPERAND_SUBTITLE_SELECT_LANGUAGE,
	TCC_OPERAND_SUBTITLE_UPDATE,

	TCC_OPERAND_LCD_SET,
	TCC_OPERAND_BACKLIGHT_SET,
	TCC_OPERAND_EXTRA_SET,
	TCC_OPERAND_AUDIOLANG_SET,
	TCC_OPERAND_HDIMAUDIO_SET,

	TCC_OPERAND_CAMERA_PREVIEW,
	TCC_OPERAND_CAMERA_RECODING,

	TCC_OPERAND_CAMREC_PREVIEW,
	TCC_OPERAND_CAMERA_CAPTURE,
	TCC_OPERAND_IMAGE_ENCODE,
	TCC_OPERAND_SHOW_STREAM,
	TCC_OPERAND_SHOW_STREAM_LIST,
	TCC_OPERAND_SHOW_SELECTED_TS_STREAM_INFO,
	TCC_OPERAND_SHOW_TS_ALL_STREAM_INFO,
	TCC_OPERAND_SHOW_TS_ALL_STREAM_ESDATA,
	TCC_OPERAND_SHOW_ALL_STREAM_INFO,
	TCC_OPERAND_SHOW_ALL_AUDIO_STREAM_INFO,
	TCC_OPERAND_SHOW_ALL_VIDEO_STREAM_INFO,
	TCC_OPERAND_SHOW_ALL_SUBTITLE_STREAM_INFO,
	TCC_OPERAND_SELECT_STREAM,
	TCC_OPERAND_CHANGE_STREAM,

	TCC_OPERAND_CHANGE_HDMI,
	TCC_OPERAND_CHANGE_OUTPUT_MODE,
	TCC_OPERAND_IMAGE_DISPLAY_OUTPUT_SET,
	TCC_OPERAND_MOTION_GIF,

	#if defined(TCC_BROADCAST_ATSC_INCLUDE) || defined(TCC_BROADCAST_DVBT_INCLUDE)
	TCC_OPERAND_CHANGE_INPUT_SOURCE,
	TCC_OPERAND_STOP_SERVICE,
	TCC_OPERAND_EPG_UPDATE,
	TCC_OPERAND_TIME_UPDATE,
	TCC_OPERAND_SIGNAL_STATUS,
	TCC_OPERAND_SERVICE_STATUS,
	TCC_OPERAND_SCRAMBLED_STATUS,
	TCC_OPERAND_RESET_DEMOD,
	TCC_OPERAND_SET_ASPECT_RATIO,
	TCC_OPERAND_AUDIOVIDEO_INFO,
	TCC_OPERAND_SET_AUDIOLANGUAGE,
	TCC_OPERAND_ENABLE_CLOSECAPTION,
	#endif

	#ifdef TCC_BROADCAST_DVBH_INCLUDE
	TCC_OPERAND_SHOW,
	TCC_OPERAND_ADD_IP_DATAGRAM,
	TCC_OPERAND_REMOVE_IP_DATAGRAM,
	#endif

//	#ifdef TCC_DXB_ISDBT_FULLSEG_INCLUDE
//	#endif

	TCC_OPERAND_IND_SCANDONE,
	TCC_OPERAND_IND_SCANSINGLEDONE,
	TCC_OPERAND_IND_SEARCH_MINMAXINDEX,
	TCC_OPERAND_IND_SEARCH_PROGRESS,
	TCC_OPERAND_IND_SETDONE,
	TCC_OPERAND_IND_STOPPLAYDONE,
	TCC_OPERAND_IND_STOPHANDOVERDONE,
	TCC_OPERAND_IND_RECORDSTARTDONE,
	TCC_OPERAND_IND_RECORDSTOPDONE,
	TCC_OPERAND_IND_RECORDTIMEUPDATE,
	TCC_OPERAND_IND_RECORDNOTIFYERROR,
	TCC_OPERAND_IND_RECORDNOTIFYINFO,
	TCC_OPERAND_IND_FILEPLAYSTARTDONE,
	TCC_OPERAND_IND_FILEPLAYSTOPDONE,
	TCC_OPERAND_IND_FILEPLAYSETPAUSEDONE,
	TCC_OPERAND_IND_FILEPLAYSETSEEKDONE,
	TCC_OPERAND_IND_FILEPLAYSETMODEDONE,
	TCC_OPERAND_IND_FILEPLAYTOTALTIMEUPDATE,
	TCC_OPERAND_IND_FILEPLAYTIMEUPDATE,
	TCC_OPERAND_IND_FILEPLAYNOTIFYERROR,
	TCC_OPERAND_IND_DELETEALLDBDONE,
	TCC_OPERAND_IND_DELETECHANNELDBDONE,
	TCC_OPERAND_IND_TUNERSIGNALSTRENGTH,
	TCC_OPERAND_IND_EPGDONE,				/* reponse to TCC_OPERAND_EPG_UPDATE */
	TCC_OPERAND_IND_EPGUPDATED,				/* notify EPG updated */
	TCC_OPERAND_IND_LOGOIMAGEUPDATED,				/* notify logo image updated */
	TCC_OPERAND_IND_CHANGE_BCAS_CARD_STATUS,
	TCC_OPERAND_IND_SERVICE_TIME_INFO,
	TCC_OPERAND_IND_PARENTLOCK_INFO,
	TCC_OPERAND_IND_CHANGE_DUAL_CHANNEL,
	TCC_OPERAND_IND_EWS_TUNER_FLAG,
	TCC_OPERAND_IND_HANDOVER_FLAG,
	TCC_OPERAND_IND_HANDOVER_PROGRESS,
	TCC_OPERAND_IND_HANDOVER_FOUND_CHANNEL,
	TCC_OPERAND_IND_CHANNEL_DB_UPDATED_ON_HANDOVER,
	TCC_OPERAND_IND_CHANNEL_DB_UPDATED_ON_AIRPLAY,
	TCC_OPERAND_IND_CHANNEL_INFO_UPDATED,
	TCC_OPERAND_IND_CHANNEL_AUDIO_TOTAL_CHANGED,
	TCC_OPERAND_IND_SERVICE_ALIVE_READY,
	TCC_OPERAND_IND_EWS_MESSAGE,
	TCC_OPERAND_IND_SOC_DEBUG_INFO,

	TCC_OPERAND_SCANSTOP,
	TCC_OPERAND_SCANSINGLE,
	TCC_OPERAND_RECORD,
	TCC_OPERAND_RECORDSTOP,
	TCC_OPERAND_FILEPLAY,
	TCC_OPERAND_FILEPLAYSTOP,
	TCC_OPERAND_FILEPLAYPAUSE,
	TCC_OPERAND_FILEPLAYSEEK,
	TCC_OPERAND_FILEPLAYMODE,
	TCC_OPERAND_PRESET,
	TCC_OPERAND_SHOW_CHANNEL_LIST,
	TCC_OPERAND_SHOW_CHANNEL_INFO,
	TCC_OPERAND_EPG_UPDATE,					/* command to update SQL EPG table */
		/* for DxB */
	TCC_OPERAND_PREPARE, //
	TCC_OPERAND_START, //
//	TCC_OPERAND_STOP, //Already exist
	TCC_OPERAND_START_TEST_MODE,
	TCC_OPERAND_RELEASE,
	TCC_OPERAND_CHANNEL_BACKUP,
	TCC_OPERAND_CHANNEL_DB_RESTORATION,
//	TCC_OPERAND_SEARCH, //Replaced TCC_OPERAND_SCAN
	TCC_OPERAND_SCAN_STOP, //	TCC_OPERAND_SEARCH_CANCEL,
	TCC_OPERAND_SET_EPG,
	TCC_OPERAND_EPG_SEARCH,
	TCC_OPERAND_EPG_SEARCH_CANCEL,
	TCC_OPERAND_MANUAL_SEARCH,
	TCC_OPERAND_RELEASE_SURFACE,
	TCC_OPERAND_USE_SURFACE,
	TCC_OPERAND_SET_COUNTRYCODE,
	TCC_OPERAND_SET_GROUP,
	TCC_OPERAND_SET_AUDIO,
	TCC_OPERAND_SET_AUDIO_MUTE,
	TCC_OPERAND_SET_VIDEO,
	TCC_OPERAND_SET_AUDIO_MUTE_ONOFF,
	TCC_OPERAND_SET_AUDIO_ONOFF,
	TCC_OPERAND_SET_VIDEO_ONOFF,
	TCC_OPERAND_SET_VIDEO_VIS_ONOFF,
	TCC_OPERAND_SET_AV_SYNC_MODE,
	TCC_OPERAND_SET, //TCC_OPERAND_SET_CHANNEL,
	TCC_OPERAND_SET_WITHCHNUM,
	TCC_OPERAND_SET_DUAL_CHANNEL,
	TCC_OPERAND_SET_MANUAL,
	TCC_OPERAND_SET_VOLUME,
	TCC_OPERAND_SET_VOLUME_LR,
	TCC_OPERAND_SET_DISPLAY_POSITION,
	TCC_OPERAND_SET_CAPTURE,
	TCC_OPERAND_SET_RECORD,
	TCC_OPERAND_SET_RECSTOP,
	TCC_OPERAND_SET_BBMODULE_INDEX,
	TCC_OPERAND_SET_BBMODULE_INDEX_EX,
	TCC_OPERAND_SET_DMB_MODE,
	TCC_OPERAND_PLAY_SUBTITLE,
	TCC_OPERAND_PLAY_SUPERIMPOSE,
	TCC_OPERAND_PLAY_PNG,
	TCC_OPERAND_SET_SUBTITLE,
	TCC_OPERAND_SET_SUPERIMPOSE,
	TCC_OPERAND_SET_AUDIO_DUALMONO,
	TCC_OPERAND_SET_PARENTALRATE,
	TCC_OPERAND_SET_AREA,
	TCC_OPERAND_SET_PRESET,
	TCC_OPERAND_SET_HANDOVER,
	TCC_OPERAND_REQ_EPG_UPDATE,
	TCC_OPERAND_REQ_SC_INFO,
	TCC_OPERAND_SET_FREQ_BAND,
	TCC_OPERAND_SET_FIELD_LOG,
	TCC_OPERAND_SET_PLAY,
	TCC_OPERAND_SET_PLAY_STOP,
	TCC_OPERAND_SET_SEEKTO,
	TCC_OPERAND_SET_PLAY_SPEED,
	TCC_OPERAND_SET_PLAY_PAUSE,
	TCC_OPERAND_SET_PRESET_MODE,
	TCC_OPERAND_SET_USERDATA_REGIONID,
	TCC_OPERAND_SET_USERDATA_PREFECTURALCODE,
	TCC_OPERAND_SET_USERDATA_AREACODE,
	TCC_OPERAND_SET_USERDATA_POSTALCODE,
	TCC_OPERAND_START_BG,
	TCC_OPERAND_STOP_BG,
	TCC_OPERAND_EVENT_NOTIFY,

	TCC_OPERAND_SET_LISTENER,
	TCC_OPERAND_IS_PLAYING,
	TCC_OPERAND_GET_VIDEO_WIDTH,
	TCC_OPERAND_GET_VIDEO_HEIGHT,
	TCC_OPERAND_GET_SIGNAL_STRENGTH,
	TCC_OPERAND_CUSTOM_RELAY_STATION_SEARCH_REQUEST,
	TCC_OPERAND_GET_GOUNTRYCODE,
	TCC_OPERAND_GET_AUDIO_CNT,
	TCC_OPERAND_GET_CHANNEL_INFO,
	TCC_OPERAND_REQ_TRMP_INFO,
	TCC_OPERAND_GET_DURATION,
	TCC_OPERAND_GET_CURRENT_POSITION,
	TCC_OPERAND_GET_CURRENT_READ_POSITION,
	TCC_OPERAND_GET_CURRENT_WRITE_POSITION,
	TCC_OPERAND_GET_TOTAL_SIZE,
	TCC_OPERAND_GET_MAX_SIZE,
	TCC_OPERAND_GET_FREE_SIZE,
	TCC_OPERAND_GET_BLOCK_SIZE,
	TCC_OPERAND_GET_FS_TYPE,
	TCC_OPERAND_GET_DATETIME,
	TCC_OPERAND_GET_SUBTITLE_LANG_INFO,
	TCC_OPERAND_GET_USERDATA,
	TCC_OPERAND_SET_CUSTOM_TUNER,
	TCC_OPERAND_GET_CUSTOM_TUNER,
	TCC_OPERAND_GET_DCCD,
	TCC_OPERAND_GET_CAD,
	TCC_OPERAND_SET_NOTIFY_DETECT_SECTION,
	TCC_OPERAND_SEARCH_AND_SET,
	TCC_OPERAND_SET_DEVICE_KEY_UPDATE_FUNCTION,
	TCC_OPERAND_GET_VIDEO_STATE,
	TCC_OPERAND_GET_SEARCH_STATE,
	TCC_OPERAND_SET_DATASERVICE_START,
	TCC_OPERAND_CUSTOM_FILTER_START,
	TCC_OPERAND_CUSTOM_FILTER_STOP,
	TCC_OPERAND_EWS_START,
	TCC_OPERAND_EWS_START_WITHCHNUM,
	TCC_OPERAND_EWS_CLEAR,
	TCC_OPERAND_SET_SEAMLESS_SWITCH_COMPENSATION,
	TCC_OPERAND_DS_GET_STC,
	TCC_OPERAND_DS_GET_SERVICETIME,
	TCC_OPERAND_DS_GET_CONTENTID,
	TCC_OPERAND_DS_CHECK_EXISTCOMPONENTTAGINPMT,
	TCC_OPERAND_DS_SET_VIDEOBYCOMPONENTTAG,
	TCC_OPERAND_DS_SET_AUDIOBYCOMPONENTTAG,
	TCC_OPERAND_GET_SEAMLESSVALUE
}TCC_OPERAND_TYPE;

typedef enum
{
	TCC_CAMERA_OPERAND_NULL = 0,
	TCC_CAMERA_OPERAND_INFO,
	TCC_CAMERA_OPERAND_OPEN,
	TCC_CAMERA_OPERAND_CLOSE,
	TCC_CAMERA_OPERAND_AUDIO,
	TCC_CAMERA_OPERAND_VIDEO,
	TCC_CAMERA_OPERAND_MUX,
	TCC_CAMERA_OPERAND_FILTER,
	TCC_CAMERA_OPERAND_OFF,
	TCC_CAMERA_OPERAND_ON,
	TCC_CAMERA_OPERAND_EVENT,
	TCC_CAMERA_OPERAND_RUN_STOP,
	TCC_CAMERA_OPERAND_PREVIEW,
	TCC_CAMERA_OPERAND_RECODE,
	TCC_CAMERA_OPERAND_CAPTURE,
	TCC_CAMERA_OPERAND_STOP,
	TCC_CAMERA_OPERAND_FILE_NAME,

	TCC_CAMERA_OPERAND_FRAMERESOLUTION,
	TCC_CAMERA_OPERAND_FRAMERATE,
	TCC_CAMERA_OPERAND_BITRATE,
	TCC_CAMERA_OPERAND_BITPERSAMPLE,
	TCC_CAMERA_OPERAND_AUDIO_ONOFF,
	TCC_CAMERA_OPERAND_AUDIO_MUTE,
//	TCC_CAMERA_OPERAND_SAMPLINGRATE,
	TCC_CAMERA_OPERAND_AUDIO_CODEC,
	TCC_CAMERA_OPERAND_VIDEO_CODEC,
	TCC_CAMERA_OPERAND_AUDIO_INPUT_TYPE,
	TCC_CAMERA_OPERAND_KEYFRAME_INTERVAL,

#ifdef TCC_CAMERA_MD_INCLUDE
	TCC_CAMERA_OPERAND_MOTION_DETECTION,
	TCC_CAMERA_OPERAND_SET_MOTION_DETECTION,
#endif
#ifdef TCC_CAMERA_JPEGENC_INCLUDE
	TCC_CAMERA_OPERAND_SET_CAPTURE_JPEG,
#endif

	TCC_CAMERA_OPERAND_FILE_UPDATE,
	TCC_CAMERA_OPERAND_EVENT_START_TIME,
	TCC_CAMERA_OPERAND_EVENT_END_TIME,
	TCC_CAMERA_OPERAND_AUTO_REC_TIME,
	TCC_CAMERA_OPERAND_BASE_TIME,

	TCC_CAMERA_OPERAND_EXTEND_DISPLAY_MODE,
	TCC_CAMERA_OPERAND_STOP_IND,
	TCC_CAMERA_OPERAND_ERROR_IND,
	TCC_CAMERA_OPERAND_MD_DRAW_IND,

	TCC_CAMERA_OPERAND_GSENSOR_SEND_DATA = 100,
	TCC_CAMERA_OPERAND_GSENSOR_SEND_DETECTED,
	TCC_CAMERA_OPERAND_GSENSOR_EXIT,

	TCC_CAMERA_OPERAND_GPS_SEND_DATA= 200,
	TCC_CAMERA_OPERAND_GPS_EXIT ,

	TCC_CAMERA_OPERAND_ETC_SET_FILE= 300,
	TCC_CAMERA_OPERAND_ETC_FORMAT,
	TCC_CAMERA_OPERAND_ETC_EXIT,
#ifdef TCC_CAMERA_SD_INCLUDE
	TCC_CAMERA_OPERAND_ETC_HOTPLUG_DEVICE_INOUT,
#endif

	TCC_CAMERA_OPERAND_STOP_FOR_OFF,
	TCC_CAMERA_OPERAND_STOP_FOR_EXIT,
	TCC_CAMERA_OPERAND_EXIT,
	TCC_CAMERA_OPERAND_NUM
}	TCC_CAMERA_OPERAND_TYPE;

typedef enum
{
	TCC_CMD_PLAY_NULL = 0,
	TCC_CMD_PLAY_PATH,
	TCC_CMD_PLAY_LIST,
	TCC_CMD_PLAY_INDEX,
	TCC_CMD_PLAY_NUM
}	TCC_CMD_PLAY_TYPE;

typedef enum
{
	TCC_CMD_RECODE_NULL = 0,
	TCC_CMD_RECODE_PATH,
	TCC_CMD_RECODE_CREAT,
	TCC_CMD_RECODE_NUM
}	TCC_CMD_RECODE_TYPE;

typedef enum
{
	TCC_CMD_IMAGE_ZOOM_NULL = 0,
	TCC_CMD_IMAGE_ZOOM_OUT,
	TCC_CMD_IMAGE_ZOOM_IN,
	TCC_CMD_IMAGE_ZOOM_NUM
}	TCC_CMD_IMAGE_ZOOM_TYPE;

typedef enum
{
	TCC_CMD_IMAGE_SLIDE_NULL = 0,
	TCC_CMD_IMAGE_SLIDE_ON,
	TCC_CMD_IMAGE_SLIDE_OFF,
	TCC_CMD_IMAGE_SLIDE_NUM
}	TCC_CMD_IMAGE_SLIDE_TYPE;

typedef enum
{
	TCC_CMD_IMAGE_ROTATION_NULL = 0,
	TCC_CMD_IMAGE_ROTATION_CW,	// Clockwise
	TCC_CMD_IMAGE_ROTATION_CCW,	// CounterClockwise
	TCC_CMD_IMAGE_ROTATION_NUM
}	TCC_CMD_IMAGE_ROTATION_TYPE;

typedef enum
{
	TCC_CMD_IMAGE_STOP_NULL = 0,
	TCC_CMD_IMAGE_STOP_PLAY,
	TCC_CMD_IMAGE_STOP_NEXT,
	TCC_CMD_IMAGE_STOP_PREV,
	TCC_CMD_IMAGE_STOP_ROTCW,
	TCC_CMD_IMAGE_STOP_ROTCCW,
	TCC_CMD_IMAGE_STOP_SLIDE_ON,
	TCC_CMD_IMAGE_STOP_SLIDE_OFF,
	TCC_CMD_IMAGE_STOP_FRAME_SET
}	TCC_CMD_IMAGE_STOPCALL_TYPE;

typedef enum
{
	TCC_CMD_SEEK_NULL = 0,
	TCC_CMD_SEEK_NORMAL,
	TCC_CMD_SEEK_VALUE,
	TCC_CMD_SEEK_NUM
}	TCC_CMD_SEEK_TYPE;

typedef enum
{
	TCC_CMD_SEEK_DIR_NULL = 0,
	TCC_CMD_SEEK_FF,
	TCC_CMD_SEEK_REW,
	TCC_CMD_SEEK_DIR_NUM
}	TCC_CMD_SEEK_DIR_TYPE;

typedef enum
{
	TCC_CMD_SEEK_MODE_DEFAULT = 0,	// Keyframe seek
	TCC_CMD_SEEK_MODE_ACCURACY,
	TCC_CMD_SEEK_MODE_NUM
}	TCC_CMD_SEEK_MODE_TYPE;

typedef enum
{
	TCC_CMD_SCAN_DIR_NULL = 0,
	TCC_CMD_SCAN_FF,
	TCC_CMD_SCAN_REW,
	TCC_CMD_SCAN_DIR_NUM
}	TCC_CMD_SCAN_DIR_TYPE;

typedef enum
{
	TCC_CMD_PLAYLIST_DEFAULT = 0,
	TCC_CMD_PLAYLIST_FOLDER,
	TCC_CMD_PLAYLIST_FILE
}	TCC_CMD_PLAYLIST_TYPE;

typedef enum
{
	TCC_CMD_EFFECT_NULL = 0,
	TCC_CMD_EFFECT_LOCK,
	TCC_CMD_EFFECT_JAZZ,
	TCC_CMD_EFFECT_NUM
}	TCC_CMD_EFFECT_TYPE;

typedef enum
{
	TCC_CMD_ISDBT_NULL = 0,
	TCC_CMD_ISDBT_STREAM,
	TCC_CMD_ISDBT_FILE,
	TCC_CMD_ISDBT_NUM
}	TCC_CMD_ISDBT_TYPE;

typedef enum
{
	TCC_CMD_DVBT_NULL = 0,
	TCC_CMD_DVBT_STREAM,
	TCC_CMD_DVBT_FILE,
	TCC_CMD_DVBT_NUM
}	TCC_CMD_DVBT_TYPE;

typedef enum
{
	TCC_CMD_TDMB_NULL = 0,
	TCC_CMD_TDMB_STREAM,
	TCC_CMD_TDMB_FILE,
	TCC_CMD_TDMB_NUM
}	TCC_CMD_TDMB_TYPE;

typedef enum
{
	TCC_CMD_AB_START = 0,
	TCC_CMD_AB_END,
	TCC_CMD_AB_CLEAR,
	TCC_CMD_AB_NUM
}	TCC_CMD_AB_REPEAT_TYPE;

typedef enum
{
	TCC_CMD_ERROR_STATE = 0x10000000,	// wrong State
	TCC_CMD_ERROR_NOT_FILE,				// when a use set wrong file name
	TCC_CMD_ERROR_NOT_FOLDER,			//when a use set wrong folder name
	TCC_CMD_ERROR_NO_MORE_FILE,			//when automatically playback, there aren't any more contents
	TCC_CMD_ERROR_NOT_SUPORT_FORMAT,	//when the contents isn't supported format
	TCC_CMD_ERROR_NOT_SUPORT_AUDIO,		//when the contents have the not supported audio
	TCC_CMD_ERROR_NOT_SUPORT_VIDEO,		//when the contents have the not supported video
	TCC_CMD_ERROR_NO_FILE,				//when there are no file in playlist folder
	TCC_CMD_ERROR_NO_REPEAT,			// PlayList End when no repeat
	TCC_CMD_ERROR_TRACK_END,			// Track End when one track repeat or total track is one
	TCC_CMD_ERROR_START_TIME,			// When AB Repeate, There aren't Star Time
	TCC_CMD_ERROR_NO_START_TIME,		// When AB Repeate, There aren't Star Time
	TCC_CMD_ERROR_NOT_OPTION,			// when a use set wrong cmd option
	TCC_CMD_ERROR_DO_NOT_OPERATION,
	TCC_CMD_ERROR_SEEK_TIME,
	TCC_CMD_ERROR_ALBUMART_DEC,

#ifdef TCC_GUI_INCLUDE
	TCC_CMD_ERROR_NOT_SELECTED_PLAYLIST,
	TCC_CMD_ERROR_EMPTY_PLAYLIST,
#endif

	TCC_CMD_ERROR_ZOOMLIMIT,
	TCC_CMD_ERROR_PANLIMIT,
	TCC_CMD_ERROR_SMALL_IMAGE,
	TCC_CMD_ERROR_NOT_SUPPORT_TYPE,
	TCC_CMD_ERROR_NO_SEEK,
	TCC_CMD_ERROR_NOT_SUPORT_THUMB_FORMAT,

	/* Audio */
	TCC_CMD_ERROR_DRM_AUDIO,

	TCC_CMD_ERROR_FILE_OPEN_FAILED = 0x90000001,
	TCC_CMD_ERROR_FILE_CLOSED_FAILED,
	TCC_CMD_ERROR_FILE_READ_FAILED,
	TCC_CMD_ERROR_MEMALLOC_FAILED,
	TCC_CMD_ERROR_NO_IMAGEDATA,
	TCC_CMD_ERROR_BUFFER_OVERFLOW,
	TCC_CMD_ERROR_EXTDATA_FAILED,
	TCC_CMD_ERROR_AUDIO_PORT_PARAMSETTING_FAILED,
	TCC_CMD_ERROR_VIDEO_PORT_PARAMSETTING_FAILED,
	TCC_CMD_ERROR_APP_PRIV_MEMALLOC_FAILED,
	TCC_CMD_ERROR_COMPONENT_LOADING_FAILED,
	TCC_CMD_ERROR_SETUP_TUNNELING_FAILED,
	TCC_CMD_ERROR_COMPONENT_EXECUTING_FAILED,
	TCC_CMD_ERROR_GET_ONEFRAME_FAILED,
	TCC_CMD_ERROR_GET_EXTINDEX_FAILED,
	TCC_CMD_ERROR_GET_EXTDATA_FAILED,
	TCC_CMD_ERROR_SET_EXTDATA_FAILED,
	TCC_CMD_ERROR_PORT_ENABLE_FAILED,
	TCC_CMD_ERROR_PORT_DISABLE_FAILED,
	TCC_CMD_ERROR_PORT_FLUSH_FAILED,
	TCC_CMD_ERROR_TIME_REQUESET_FAILED,
	TCC_CMD_ERROR_SEMA_TIMER_EXPIRE,
	TCC_CMD_ERROR_CODEC_OPEN_FAILED,
	TCC_CMD_ERROR_CODEC_CLOSED_FAILED,
	TCC_CMD_ERROR_INVALIDINFO,
	TCC_CMD_ERROR_INVALIDFILE,
	TCC_CMD_ERROR_SET_OUTPUT_FAILED,
	TCC_CMD_ERROR_EXTRAMODE_FAILED,
	TCC_CMD_ERROR_AUDIO_CODECOPEN_FAILED,
	TCC_CMD_ERROR_DECODING_FAILED,
	TCC_CMD_ERROR_DMX_DATA_FULL_ERROR,

	// for rec
	TCC_CMD_ERROR_REC_FILEOPEN_FAIL,
	TCC_CMD_ERROR_REC_FILECLOS_FAIL,

	// for image
	TCC_CMD_ERROR_IMAGE_GET_ORGSIZE_FAILED,
	TCC_CMD_ERROR_IMAGE_SET_OUTWITDH,
	TCC_CMD_ERROR_IMAGE_SET_OUTHEIGHT,
	TCC_CMD_ERROR_IMAGE_SET_THUMB_OFFSET,
	TCC_CMD_ERROR_IMAGE_SET_OUTBUFFER_POINTER,
	TCC_CMD_ERROR_IMAGE_SET_OUTFORMAT,
	TCC_CMD_ERROR_IMAGE_SAVEAS,
	TCC_CMD_ERROR_UNSUPPORTED_IMAGE,

	// for Broadcasting
	TCC_CMD_ERROR_TDMB_FREQUENCY_SET_FAIL,
	TCC_CMD_ERROR_TDMB_SERVICE_SET_FAIL,
	TCC_CMD_ERROR_TDMB_TS_DATA,
	TCC_CMD_ERROR_TDMB_WEEKSIGNAL,
	TCC_CMD_ERROR_TDMB_DAB_DATA,

	/* VIDEO */
	TCC_CMD_ERROR_UNSUPPORTED_FORMAT = 0x90001000,
	TCC_CMD_ERROR_UNSUPPORTED_COMBINATION,
	TCC_CMD_ERROR_UNSUPPORTED_VIDEO,
	TCC_CMD_ERROR_UNSUPPORTED_VIDEO_SIZE,
	TCC_CMD_ERROR_UNSUPPORTED_VIDEO_FRAMERATE,
	TCC_CMD_ERROR_UNSUPPORTED_AUDIO,
	TCC_CMD_ERROR_NO_VIDEO_STREAM,
	TCC_CMD_ERROR_NO_AUDIO_STREAM,
	TCC_CMD_ERROR_DEMUXER_INIT_ERROR,
	TCC_CMD_ERROR_DEMUXER_GETINFO_ERROR,
	TCC_CMD_ERROR_DEMUXER_DEINIT_ERROR,
	TCC_CMD_ERROR_DEMUXER_GETSTREAM_ERROR,
	TCC_CMD_ERROR_VPU_INIT_ERROR,
	TCC_CMD_ERROR_VPU_MEMORY_ERROR,
	TCC_CMD_ERROR_VPU_SEQ_ERROR,
	TCC_CMD_ERROR_CDK_INIT_ERROR,
	TCC_CMD_ERROR_CDK_SET_IO_ERROR,
	TCC_CMD_ERROR_M2M_SCALER_ERROR,
	TCC_CMD_ERROR_G2D_ERROR,
	TCC_CMD_ERROR_UNSUPPORTED_SEEK_ERROR,
	TCC_CMD_ERROR_UNSUPPORTED_SCAN_ERROR,
	TCC_CMD_ERROR_INVALID_APP_STATE,
	TCC_CMD_ERROR_BROKEN_FILE_ERROR,
	TCC_CMD_ERROR_NOTSUPPORT_SUBTITLE,

	/* CAMERA */
	TCC_CMD_ERROR_INVALID_OPERATION = 0x90005000,
	TCC_CMD_ERROR_INVALID_PARAMETER,
	TCC_CMD_ERROR_INVALID_STATE,
	TCC_CMD_ERROR_DONOT_RECODING,
	TCC_CMD_ERROR_SAME_STATE,
	TCC_CMD_ERROR_SAME_PARAMETER,
	TCC_CMD_ERROR_DONOT_EVENT_RECODING_COMPLETE,


	// for Hotplug device disconnect msg
	TCC_CMD_PLUGOUT_SDCARD,
	TCC_CMD_PLUGOUT_OTG,
	TCC_CMD_PLUGOUT_OHCI,

	TCC_CMD_ERROR_MAX
}	TCC_CMD_ERROR_TYPE;

typedef enum
{
	TCC_SUBTITLE_IDENTY_NONE = 0,
	TCC_SUBTITLE_IDENTY_VIDEO,
	TCC_SUBTITLE_IDENTY_AUDIO,
	TCC_SUBTITLE_IDENTY_BROADCAST,

	TCC_SUBTITLE_IDENTY_MAX
}	TCC_SUBTITLE_IDENTY_TYPE;

typedef enum
{
	TCC_SUBTITLE_STRING_NONE = 0,

#ifdef TCC_BROADCAST_TDMB_INCLUDE
	TCC_SUBTITLE_STRING_TEXT_ASCII_TYPE,
	TCC_SUBTITLE_STRING_TEXT_UNICODE_TYPE,
#else
	TCC_SUBTITLE_STRING_TEXT_TYPE,
	TCC_SUBTITLE_STRING_IMAGE_TYPE,
#endif

	TCC_SUBTITLE_TEXT_TYPE_MAX
}	TCC_SUBTITLE_TEXT_TYPE;

typedef enum
{
	TCC_SUBTITLE_MODE_NONE = 0,
	TCC_SUBTITLE_MODE_INTERNAL,
	TCC_SUBTITLE_MODE_EXTERNAL,

	TCC_SUBTITLE_MODE_MAX
}	TCC_SUBTITLE_MODE;

typedef enum
{
//	TCC_SUBTITLE_LANGUAGE_SEL_NONE 	= 0,
	TCC_SUBTITLE_LANGUAGE_SEL_1ST 	= 0,
	TCC_SUBTITLE_LANGUAGE_SEL_2ND,
	TCC_SUBTITLE_LANGUAGE_SEL_3TH,

	TCC_SUBTITLE_LANGUAGE_SEL_MAX
}	TCC_SUBTITLE_LANGUAGE;

/******************************************************************************
* globals
******************************************************************************/
typedef struct TCC_AB_Repeat_Structure
{
	int 			Flag;
	unsigned int 	Start;
	unsigned int 	End;
}	TCC_AB_Repeat_t, *pTCC_AB_Repeat_t;

typedef struct TCC_SCAN_Mode_Structure
{
	int scale_mode;
	int scale_direction;
}	TCC_SCAN_Mode_t, *pTCC_SCAN_Mode_t;

/******************************************************************************
* locals
******************************************************************************/


/******************************************************************************
* declarations
******************************************************************************/

#endif //_TCC_COMMON_CMD_H__
